### ISSUE TITLE
update netrics image for wilson and tigerteam

### ISSUE THREAD

**Issue by ggmartins** [chicago-cdac/nm-exp-active-netrics#106]
Update linux image for netrics with the latest packages and disable unattended upgrades

**Comment by ggmartins** [comment]
Flasher 2.0 device was built and is available in the lot lab for testing with latest images for tt and Wilson. Tigerteam image is on testing at af46. Wilson image is about to get tested at home too (Everywhere Wireless).

**Comment by marcwitasee** [comment]
@ggmartins to test the wilson image this week.

**Comment by marcwitasee** [comment]
New images have been created and tested.
