### ISSUE TITLE
add vca performance measurements to the Netrics test suite

### ISSUE THREAD

**Issue by tarunmangla** [chicago-cdac/nm-exp-active-netrics#107]
Goal: We want to be able to measure performance of video conferencing applications in the households. 
Approach: Run VCA calls from the households to another endpoint located in the university
Tasks:
- [ ] Automation framework for VCA call setup on Raspi
- [ ] Integration with the current Netrics scheduler
- [ ] Integration with the Netrics 2.0

**Comment by marcwitasee** [comment]
Redundant with issues in VCA repository.
