### ISSUE TITLE
Wrong units on Ookla speedtest

### ISSUE THREAD

**Issue by JamesSaxon** [chicago-cdac/nm-exp-active-netrics#15]
The Ookla speedtest "bandwidth" in the json is in bytes, not bits.  So to answer the question in the code, it's: `* 8 / 1e6`:

https://github.com/chicago-cdac/nm-exp-active-netrics/blob/52c184c6587e6a5e56cb4fd9ff253bd4cccf5206/src/netrics/netson.py#L109

If you compare my dashboard, you can see that it's therefore 25% high...

@ggmartins please fix this one?

**Comment by ggmartins** [comment]
see if 8d78862 works, thanks, G

**Comment by JamesSaxon** [comment]
Yep, that's all the changes I made in my copy, and it's running fine.
