### ISSUE TITLE
purging non-ookla speedtest

### ISSUE THREAD

**Issue by JamesSaxon** [chicago-cdac/nm-exp-active-netrics#16]
Probably don't want the "other" speedtest still there:

https://github.com/chicago-cdac/nm-exp-active-netrics/blob/8d7886230448a6e95988935d3be1a4dc9770dedd/Makefile#L38

I think this is causing issues for me, on the ubuntu install.

**Comment by ggmartins** [comment]
b5017e0

for the record, speedtest bin is now shipped with the whole thing
