### ISSUE TITLE
iperf3.sh name?

### ISSUE THREAD

**Issue by JamesSaxon** [chicago-cdac/nm-exp-active-netrics#17]
At least in ubuntu, it looks like I can just point to iperf3, instead of iperf3.sh.  The latter are giving me errors, and everything is fine without the .sh.

https://github.com/chicago-cdac/nm-exp-active-netrics/blob/8d7886230448a6e95988935d3be1a4dc9770dedd/src/netrics/netson.py#L229
https://github.com/chicago-cdac/nm-exp-active-netrics/blob/8d7886230448a6e95988935d3be1a4dc9770dedd/src/netrics/netson.py#L476

**Comment by ggmartins** [comment]
potentially fixed, needs testing on "non-dev" install
