### ISSUE TITLE
hardware evaluation

### ISSUE THREAD

**Issue by ggmartins** [chicago-cdac/nm-exp-active-netrics#24]
Description: we need to know the best hardware to use for Phase 1 deployment considering both passive and active measurements enabled
Requirements:
- Microtik
- Ubqt ER-X
- tp-link 5-port switch
- netgear 5-port swtich
- Wifi routers (wifi6 ideally)
- 1Gbps connection

Goals:
- Decide Microtik vs ER-X
- Decide tp-link vs netgear switches
- Device on the best wifi router
- The ideal hardware must produce stable lines for longitudinal speedtest/ndt7 measurements with <%1 Retransmission rate

**Comment by JamesSaxon** [comment]
I think a lot of this is less pertinent or high-priority, if we're starting from pi's?
