### ISSUE TITLE
Deployment Workflow Documentation

### ISSUE THREAD

**Issue by ggmartins** [chicago-cdac/nm-exp-active-netrics#25]
Description: Divided into 2 documents:
- Network Measurement Box Assembly
- Device Deployment and Activation
Requirements:
- cms, active-netrics, passive-netrics, local dash packages tested and validated
- The definition of both hardware and software to be (pre) installed
- The definition of "if" or "when" to link random id to time participants email (and the box assembly time? or via GUI survey?)
- The definition of the box layout
- Content (?)

Goals:
- with this documentation, someone can start assembling and delivering the measurement boxes

**Comment by marcwitasee** [comment]
I think that we have thought through most of the items in this issue. I think now it is a matter of compiling all of this information into a single shareable document.
