### ISSUE TITLE
Add device identification test

### ISSUE THREAD

**Issue by kyle-macmillan** [chicago-cdac/nm-exp-active-netrics#56]
Could be insightful to see if we can map MAC addrs to the type of device. Number of devices doesn't really tell the whole story.

**Comment by ggmartins** [comment]
This is a major privacy issue IMHO, I wouldn't do it.

**Comment by ggmartins** [comment]
I think we decided not to implement this, right? in fact, I just disabled the arp data that we were recording in the zip.
