### ISSUE TITLE
Set up a dedicated development device in the IoT Lab

### ISSUE THREAD

**Issue by marcwitasee** [chicago-cdac/nm-exp-active-netrics#95]
Should we set up a device in the IoT lab that is dedicated specifically to development? This device would serve as a place for team members to work on enhancements to the Netrics code as well as a first stage to test out fixes for bugs. It would be accessible to our team and collaborators only.

**Comment by marcwitasee** [comment]
@ggmartins does the IoT lab device already somewhat fulfill this purpose?

**Comment by ggmartins** [comment]
I think so
